"""
Temporary script to update S1.py with JSON-based coordinates.
This script will be deleted after updating S1.py.
"""

# This is the new coordinate structure based on the JSON file
PTW_COORDINATES_JSON = """
# JSON-based coordinate mapping for PDF overlay (loaded from ptw_coordinates.json)
# Structure: page_N -> {text_fields, checkboxes, tri_state_checkboxes, signatures, stamp_anchor}
# All coordinates are in PDF points (A4: 595 x 842, bottom-left origin)

_PTW_COORDINATES = {
    "page_1": {
        "text_fields": {
            "doc_no": {"x": 480, "y": 810, "max_width": 100},
            "rev_dt": {"x": 480, "y": 795, "max_width": 100},
            "permit_no": {"x": 120, "y": 780, "max_width": 100},
            "permit_validity_date": {"x": 280, "y": 780, "max_width": 120},
            "start_time": {"x": 430, "y": 780, "max_width": 70},
            "end_time": {"x": 520, "y": 780, "max_width": 70},
            "project_site_name": {"x": 120, "y": 755, "max_width": 220},
            "work_location": {"x": 380, "y": 755, "max_width": 200},
            "description_of_work": {"x": 120, "y": 730, "max_width": 460},
            "contractor_name": {"x": 120, "y": 705, "max_width": 460},
            "hazards_others_text": {"x": 510, "y": 600, "max_width": 70},
            "risk_others_text": {"x": 510, "y": 525, "max_width": 70},
            "ppe_others_text": {"x": 510, "y": 390, "max_width": 70},
            "safety_precautions_others_text": {"x": 510, "y": 330, "max_width": 70},
        },
        "checkboxes": {
            "hazards.live_dc_cables": {"x": 55, "y": 660},
            "hazards.high_dc_voltage": {"x": 55, "y": 645},
            "hazards.arc_flash": {"x": 55, "y": 630},
            "hazards.improper_grounding": {"x": 55, "y": 615},
            "hazards.overloaded_circuits": {"x": 55, "y": 600},
            "hazards.working_at_height": {"x": 55, "y": 585},
            "hazards.loose_damaged_connectors": {"x": 200, "y": 660},
            "hazards.poor_grounding": {"x": 200, "y": 645},
            "hazards.working_at_height_rooftop": {"x": 200, "y": 630},
            "hazards.wet_surfaces": {"x": 200, "y": 615},
            "hazards.manual_handling": {"x": 200, "y": 600},
            "hazards.moving_tracker_parts": {"x": 345, "y": 660},
            "hazards.heavy_solar_panels": {"x": 345, "y": 645},
            "hazards.sharp_panel_edges": {"x": 345, "y": 630},
            "hazards.high_ambient_temperature": {"x": 345, "y": 615},
            "hazards.overhead_line": {"x": 345, "y": 600},
            "hazards.dust_accumulation": {"x": 490, "y": 660},
            "hazards.wildlife": {"x": 490, "y": 645},
            "hazards.lightning_stormy": {"x": 490, "y": 630},
            "hazards.others": {"x": 490, "y": 600},
            "risk_identification.electrocution": {"x": 55, "y": 555},
            "risk_identification.electric_shock": {"x": 55, "y": 540},
            "risk_identification.electric_burn": {"x": 55, "y": 525},
            "risk_identification.bites_stings": {"x": 55, "y": 510},
            "risk_identification.falling_particles": {"x": 55, "y": 495},
            "risk_identification.tripping_slipping": {"x": 55, "y": 480},
            "risk_identification.burns_equipment_damage": {"x": 200, "y": 555},
            "risk_identification.fire_overheating": {"x": 200, "y": 540},
            "risk_identification.fall_serious_injury": {"x": 200, "y": 525},
            "risk_identification.unexpected_energization": {"x": 345, "y": 555},
            "risk_identification.crushing_pinching": {"x": 345, "y": 540},
            "risk_identification.back_muscle_injury": {"x": 345, "y": 525},
            "risk_identification.heat_stress": {"x": 490, "y": 555},
            "risk_identification.others": {"x": 490, "y": 525},
            "ppe.safety_helmet": {"x": 55, "y": 435},
            "ppe.safety_shoes": {"x": 55, "y": 420},
            "ppe.reflective_vest": {"x": 55, "y": 405},
            "ppe.safety_goggles": {"x": 55, "y": 390},
            "ppe.hrc_suit": {"x": 200, "y": 435},
            "ppe.electrical_mat": {"x": 200, "y": 420},
            "ppe.face_shield": {"x": 200, "y": 405},
            "ppe.insulated_hand_tools": {"x": 200, "y": 390},
            "ppe.respirators": {"x": 345, "y": 435},
            "ppe.dust_masks": {"x": 345, "y": 420},
            "ppe.ear_plugs": {"x": 345, "y": 405},
            "ppe.electrical_hand_gloves": {"x": 345, "y": 390},
            "ppe.full_body_harness": {"x": 490, "y": 435},
            "ppe.lifeline_anchor": {"x": 490, "y": 420},
            "ppe.cut_resistant_gloves": {"x": 490, "y": 405},
            "ppe.others": {"x": 490, "y": 390},
            "safety_precautions.electrical_isolation": {"x": 55, "y": 345},
            "safety_precautions.lockout_tagout": {"x": 55, "y": 330},
            "safety_precautions.zero_voltage": {"x": 55, "y": 315},
            "safety_precautions.insulated_tools": {"x": 55, "y": 300},
            "safety_precautions.fire_extinguisher": {"x": 200, "y": 345},
            "safety_precautions.warning_signage": {"x": 200, "y": 330},
            "safety_precautions.proper_earthing": {"x": 200, "y": 315},
            "safety_precautions.proper_illumination": {"x": 200, "y": 300},
            "safety_precautions.authorized_personnel": {"x": 345, "y": 345},
            "safety_precautions.rescue_equipment": {"x": 345, "y": 330},
            "safety_precautions.pre_job_meeting": {"x": 345, "y": 315},
            "safety_precautions.escape_route": {"x": 345, "y": 300},
            "safety_precautions.others": {"x": 490, "y": 330},
        },
        "stamp_anchor": {"x": 395, "y": 85, "width": 160, "height": 60},
    },
    "page_2": {
        "text_fields": {
            "doc_no": {"x": 480, "y": 810, "max_width": 100},
            "rev_dt": {"x": 480, "y": 795, "max_width": 100},
            "associated_permits.hot_work_no": {"x": 155, "y": 755, "max_width": 60},
            "associated_permits.general_work_no": {"x": 155, "y": 740, "max_width": 60},
            "associated_permits.loto_no": {"x": 155, "y": 725, "max_width": 60},
            "associated_permits.work_at_night_no": {"x": 350, "y": 755, "max_width": 50},
            "associated_permits.excavation_no": {"x": 350, "y": 740, "max_width": 50},
            "associated_permits.confined_space_no": {"x": 350, "y": 725, "max_width": 50},
            "associated_permits.work_at_height_no": {"x": 520, "y": 755, "max_width": 60},
            "associated_permits.lifting_permit_no": {"x": 520, "y": 740, "max_width": 60},
            "associated_permits.others_text": {"x": 505, "y": 725, "max_width": 75},
            "tools_equipment": {"x": 55, "y": 695, "max_width": 530},
            "checks_remarks": {"x": 120, "y": 545, "max_width": 460},
        },
        "checkboxes": {
            "associated_permits.hot_work": {"x": 55, "y": 755},
            "associated_permits.general_work": {"x": 55, "y": 740},
            "associated_permits.loto": {"x": 55, "y": 725},
            "associated_permits.work_at_night": {"x": 230, "y": 755},
            "associated_permits.excavation": {"x": 230, "y": 740},
            "associated_permits.confined_space": {"x": 230, "y": 725},
            "associated_permits.work_at_height": {"x": 405, "y": 755},
            "associated_permits.lifting_permit": {"x": 405, "y": 740},
            "associated_permits.others": {"x": 405, "y": 725},
        },
        "tri_state_checkboxes": {
            "checks_before_issue.jsa_carried_out": {"Y": {"x": 295, "y": 680}, "N": {"x": 325, "y": 680}, "NA": {"x": 355, "y": 680}},
            "checks_before_issue.equipment_deenergized": {"Y": {"x": 295, "y": 665}, "N": {"x": 325, "y": 665}, "NA": {"x": 355, "y": 665}},
            "checks_before_issue.energized_circuit_ppe": {"Y": {"x": 295, "y": 650}, "N": {"x": 325, "y": 650}, "NA": {"x": 355, "y": 650}},
            "checks_before_issue.workers_qualified": {"Y": {"x": 295, "y": 635}, "N": {"x": 325, "y": 635}, "NA": {"x": 355, "y": 635}},
            "checks_before_issue.tools_fit_to_use": {"Y": {"x": 295, "y": 620}, "N": {"x": 325, "y": 620}, "NA": {"x": 355, "y": 620}},
            "checks_before_issue.rescue_plan_available": {"x": 295, "y": 605}, "N": {"x": 325, "y": 605}, "NA": {"x": 355, "y": 605}},
            "checks_before_issue.testing_equipment_compatible": {"Y": {"x": 295, "y": 590}, "N": {"x": 325, "y": 590}, "NA": {"x": 355, "y": 590}},
            "checks_before_issue.line_clearance_taken": {"Y": {"x": 295, "y": 575}, "N": {"x": 325, "y": 575}, "NA": {"x": 355, "y": 575}},
            "checks_before_issue.environment_suitable": {"Y": {"x": 565, "y": 680}, "N": {"x": 540, "y": 680}, "NA": {"x": 515, "y": 680}},
            "checks_before_issue.firefighting_available": {"Y": {"x": 565, "y": 665}, "N": {"x": 540, "y": 665}, "NA": {"x": 515, "y": 665}},
            "checks_before_issue.rescue_equipment_available": {"Y": {"x": 565, "y": 650}, "N": {"x": 540, "y": 650}, "NA": {"x": 515, "y": 650}},
            "checks_before_issue.electrical_equipment_grounded": {"Y": {"x": 565, "y": 635}, "N": {"x": 540, "y": 635}, "NA": {"x": 515, "y": 635}},
            "checks_before_issue.adequate_lighting": {"Y": {"x": 565, "y": 620}, "N": {"x": 540, "y": 620}, "NA": {"x": 515, "y": 620}},
            "checks_before_issue.warning_signage_available": {"Y": {"x": 565, "y": 605}, "N": {"x": 540, "y": 605}, "NA": {"x": 515, "y": 605}},
            "checks_before_issue.conductive_items_removed": {"Y": {"x": 565, "y": 590}, "N": {"x": 540, "y": 590}, "NA": {"x": 515, "y": 590}},
            "checks_before_issue.safety_explained_to_crew": {"Y": {"x": 565, "y": 575}, "N": {"x": 540, "y": 575}, "NA": {"x": 515, "y": 575}},
        },
    },
    "page_3": {
        "text_fields": {
            "doc_no": {"x": 480, "y": 810, "max_width": 100},
            "rev_dt": {"x": 480, "y": 795, "max_width": 100},
        },
        "signatures": {
            "undertaking.permit_receiver.name": {"x": 55, "y": 640, "max_width": 150},
            "undertaking.permit_receiver.signature": {"x": 220, "y": 640, "max_width": 150},
            "undertaking.permit_receiver.datetime": {"x": 385, "y": 640, "max_width": 150},
            "undertaking.permit_holder.name": {"x": 55, "y": 620, "max_width": 150},
            "undertaking.permit_holder.signature": {"x": 220, "y": 620, "max_width": 150},
            "undertaking.permit_holder.datetime": {"x": 385, "y": 620, "max_width": 150},
            "coworkers.name_1": {"x": 55, "y": 585, "max_width": 80},
            "coworkers.name_2": {"x": 150, "y": 585, "max_width": 80},
            "coworkers.name_3": {"x": 245, "y": 585, "max_width": 80},
            "coworkers.name_4": {"x": 55, "y": 570, "max_width": 80},
            "coworkers.name_5": {"x": 150, "y": 570, "max_width": 80},
            "coworkers.name_6": {"x": 245, "y": 570, "max_width": 80},
            "approval.permit_issuer.name": {"x": 55, "y": 525, "max_width": 200},
            "approval.permit_issuer.signature": {"x": 270, "y": 525, "max_width": 150},
            "approval.permit_issuer.datetime": {"x": 435, "y": 525, "max_width": 145},
            "extension.date": {"x": 55, "y": 460, "max_width": 70},
            "extension.time_from": {"x": 140, "y": 460, "max_width": 50},
            "extension.time_to": {"x": 205, "y": 460, "max_width": 50},
            "extension.permit_holder_name": {"x": 270, "y": 460, "max_width": 70},
            "extension.permit_holder_signature": {"x": 355, "y": 460, "max_width": 65},
            "extension.permit_receiver_name": {"x": 435, "y": 460, "max_width": 70},
            "extension.permit_receiver_signature": {"x": 520, "y": 460, "max_width": 60},
            "extension.permit_issuer_name": {"x": 55, "y": 440, "max_width": 70},
            "extension.permit_issuer_signature": {"x": 140, "y": 440, "max_width": 60},
            "extension.remarks": {"x": 120, "y": 410, "max_width": 460},
        },
    },
    "page_4": {
        "text_fields": {
            "doc_no": {"x": 480, "y": 810, "max_width": 100},
            "rev_dt": {"x": 480, "y": 795, "max_width": 100},
        },
        "signatures": {
            "closure.permit_receiver.name": {"x": 55, "y": 710, "max_width": 150},
            "closure.permit_receiver.signature": {"x": 220, "y": 710, "max_width": 150},
            "closure.permit_receiver.datetime": {"x": 385, "y": 710, "max_width": 150},
            "closure.permit_holder.name": {"x": 55, "y": 690, "max_width": 150},
            "closure.permit_holder.signature": {"x": 220, "y": 690, "max_width": 150},
            "closure.permit_holder.datetime": {"x": 385, "y": 690, "max_width": 150},
            "closure.permit_issuer.name": {"x": 55, "y": 670, "max_width": 150},
            "closure.permit_issuer.signature": {"x": 220, "y": 670, "max_width": 150},
            "closure.permit_issuer.datetime": {"x": 385, "y": 670, "max_width": 150},
        },
    },
}

# Field mapping from internal form field names to JSON coordinate keys
_FIELD_TO_COORD_MAP = {
    # Page 1 text fields
    "permit_no": "permit_no",
    "permit_validity_date": "permit_validity_date",
    "start_time": "start_time",
    "end_time": "end_time",
    "site_name": "project_site_name",
    "work_location": "work_location",
    "work_description": "description_of_work",
    "contractor_name": "contractor_name",
    
    # Hazards checkboxes (hz_ -> hazards.)
    "hz_live_dc_cables": "hazards.live_dc_cables",
    "hz_high_dc": "hazards.high_dc_voltage",
    "hz_arc_flash": "hazards.arc_flash",
    "hz_improper_grounding": "hazards.improper_grounding",
    "hz_overload": "hazards.overloaded_circuits",
    "hz_working_height": "hazards.working_at_height",
    "hz_loose_connectors": "hazards.loose_damaged_connectors",
    "hz_poor_grounding": "hazards.poor_grounding",
    "hz_wet_surfaces": "hazards.wet_surfaces",
    "hz_manual_handling": "hazards.manual_handling",
    "hz_tracker_parts": "hazards.moving_tracker_parts",
    "hz_heavy_panels": "hazards.heavy_solar_panels",
    "hz_sharp_edges": "hazards.sharp_panel_edges",
    "hz_heat": "hazards.high_ambient_temperature",
    "hz_overhead_line": "hazards.overhead_line",
    "hz_dust": "hazards.dust_accumulation",
    "hz_wildlife": "hazards.wildlife",
    "hz_lightning": "hazards.lightning_stormy",
    "hz_others_text": "hazards_others_text",
    
    # Risk identification (rk_ -> risk_identification.)
    "rk_electrocution": "risk_identification.electrocution",
    "rk_electric_shock": "risk_identification.electric_shock",
    "rk_electric_burn": "risk_identification.electric_burn",
    "rk_bites": "risk_identification.bites_stings",
    "rk_falling_particles": "risk_identification.falling_particles",
    "rk_tripping": "risk_identification.tripping_slipping",
    "rk_burns": "risk_identification.burns_equipment_damage",
    "rk_fire": "risk_identification.fire_overheating",
    "rk_fall": "risk_identification.fall_serious_injury",
    "rk_unexpected_energization": "risk_identification.unexpected_energization",
    "rk_crushing": "risk_identification.crushing_pinching",
    "rk_back_injury": "risk_identification.back_muscle_injury",
    "rk_heat_stress": "risk_identification.heat_stress",
    "rk_others_text": "risk_others_text",
    
    # PPE (ppe_ -> ppe.)
    "ppe_helmet": "ppe.safety_helmet",
    "ppe_shoes": "ppe.safety_shoes",
    "ppe_reflective_vest": "ppe.reflective_vest",
    "ppe_goggles": "ppe.safety_goggles",
    "ppe_hrc_suit": "ppe.hrc_suit",
    "ppe_electrical_mat": "ppe.electrical_mat",
    "ppe_face_shield": "ppe.face_shield",
    "ppe_insulated_tools": "ppe.insulated_hand_tools",
    "ppe_respirators": "ppe.respirators",
    "ppe_dust_mask": "ppe.dust_masks",
    "ppe_ear_plugs": "ppe.ear_plugs",
    "ppe_electrical_gloves": "ppe.electrical_hand_gloves",
    "ppe_harness": "ppe.full_body_harness",
    "ppe_lifeline": "ppe.lifeline_anchor",
    "ppe_cut_gloves": "ppe.cut_resistant_gloves",
    "ppe_others_text": "ppe_others_text",
    
    # Safety precautions (sp_ -> safety_precautions.)
    "sp_electrical_isolation": "safety_precautions.electrical_isolation",
    "sp_loto": "safety_precautions.lockout_tagout",
    "sp_zero_voltage": "safety_precautions.zero_voltage",
    "sp_insulated_tools": "safety_precautions.insulated_tools",
    "sp_fire_extinguisher": "safety_precautions.fire_extinguisher",
    "sp_signage": "safety_precautions.warning_signage",
    "sp_earthing": "safety_precautions.proper_earthing",
    "sp_illumination": "safety_precautions.proper_illumination",
    "sp_authorized_personnel": "safety_precautions.authorized_personnel",
    "sp_rescue_equipment": "safety_precautions.rescue_equipment",
    "sp_pre_job_meeting": "safety_precautions.pre_job_meeting",
    "sp_escape_route": "safety_precautions.escape_route",
    "sp_others_text": "safety_precautions_others_text",
    
    # Associated permits (ap_ -> associated_permits.)
    "ap_hot_work": "associated_permits.hot_work",
    "ap_general_work": "associated_permits.general_work",
    "ap_loto": "associated_permits.loto",
    "ap_night_work": "associated_permits.work_at_night",
    "ap_excavation": "associated_permits.excavation",
    "ap_confined_space": "associated_permits.confined_space",
    "ap_height_work": "associated_permits.work_at_height",
    "ap_lifting": "associated_permits.lifting_permit",
    "ap_others_text": "associated_permits.others_text",
    
    # Tools equipment
    "tools_equipment": "tools_equipment",
    "checks_remarks": "checks_remarks",
    
    # Checkpoints (chk_ -> checks_before_issue.)
    "chk_jsa": "checks_before_issue.jsa_carried_out",
    "chk_loto": "checks_before_issue.equipment_deenergized",
    "chk_energized_ppe": "checks_before_issue.energized_circuit_ppe",
    "chk_workers_fit": "checks_before_issue.workers_qualified",
    "chk_tools": "checks_before_issue.tools_fit_to_use",
    "chk_rescue_plan": "checks_before_issue.rescue_plan_available",
    "chk_testing_equipment": "checks_before_issue.testing_equipment_compatible",
    "chk_line_clearance": "checks_before_issue.line_clearance_taken",
    "chk_environment": "checks_before_issue.environment_suitable",
    "chk_fire_fighting": "checks_before_issue.firefighting_available",
    "chk_rescue": "checks_before_issue.rescue_equipment_available",
    "chk_grounded": "checks_before_issue.electrical_equipment_grounded",
    "chk_lighting": "checks_before_issue.adequate_lighting",
    "chk_signage": "checks_before_issue.warning_signage_available",
    "chk_conductive_removed": "checks_before_issue.conductive_items_removed",
    "chk_briefing": "checks_before_issue.safety_explained_to_crew",
    
    # Page 3 signatures
    "receiver_name": "undertaking.permit_receiver.name",
    "receiver_datetime": "undertaking.permit_receiver.datetime",
    "holder_name": "undertaking.permit_holder.name",
    "holder_datetime": "undertaking.permit_holder.datetime",
    "issuer_name": "approval.permit_issuer.name",
    "issuer_datetime": "approval.permit_issuer.datetime",
    "coworker_1": "coworkers.name_1",
    "coworker_2": "coworkers.name_2",
    "coworker_3": "coworkers.name_3",
    "coworker_4": "coworkers.name_4",
    "coworker_5": "coworkers.name_5",
    "coworker_6": "coworkers.name_6",
    
    # Extension
    "ext_date": "extension.date",
    "ext_from_time": "extension.time_from",
    "ext_to_time": "extension.time_to",
    "ext_holder_name": "extension.permit_holder_name",
    "ext_receiver_name": "extension.permit_receiver_name",
    "ext_issuer_name": "extension.permit_issuer_name",
    "ext_remarks": "extension.remarks",
    
    # Closure
    "closure_receiver": "closure.permit_receiver.name",
    "closure_receiver_datetime": "closure.permit_receiver.datetime",
    "closure_holder": "closure.permit_holder.name",
    "closure_holder_datetime": "closure.permit_holder.datetime",
    "closure_issuer": "closure.permit_issuer.name",
    "closure_issuer_datetime": "closure.permit_issuer.datetime",
}

# Global coordinate offset to correct template margin/scale mismatch.
# Apply this to every drawString/textLine/tick (do not change individual coords).
X_OFFSET = -6
Y_OFFSET = 20
"""

print("Template coordinate structure created. This will be integrated into S1.py.")

